export const stockData = [
  {
    id: "1",
    name: "Digital Thermometer",
    category: "medical-devices",
    price: 29.99,
    description: "Fast and accurate digital thermometer with fever alert",
    quantity: 150,
    prescription: false,
    image: "/digital-thermometer-medical-device.jpg",
  },
  {
    id: "2",
    name: "Blood Pressure Monitor",
    category: "medical-devices",
    price: 89.99,
    description: "Automatic upper arm blood pressure monitor with large display",
    quantity: 45,
    prescription: false,
    image: "/blood-pressure-monitor-medical-device.jpg",
  },
  {
    id: "3",
    name: "Vitamin D3 Supplements",
    category: "supplements",
    price: 24.99,
    description: "60 capsules - Supports bone health and immune system",
    quantity: 300,
    prescription: false,
    image: "/vitamin-d3-supplement-bottle.jpg",
  },
  {
    id: "4",
    name: "Prescription Antibiotics",
    category: "prescription",
    price: 45.0,
    description: "Amoxicillin 500mg - Requires valid prescription",
    quantity: 80,
    prescription: true,
    image: "/prescription-medicine-bottle-antibiotics.jpg",
  },
  {
    id: "5",
    name: "First Aid Kit",
    category: "medical-supplies",
    price: 39.99,
    description: "Complete first aid kit with bandages, antiseptic, and tools",
    quantity: 120,
    prescription: false,
    image: "/first-aid-kit-medical-supplies.jpg",
  },
  {
    id: "6",
    name: "Omega-3 Fish Oil",
    category: "supplements",
    price: 32.99,
    description: "120 softgels - Supports heart and brain health",
    quantity: 0,
    prescription: false,
    image: "/omega-3-fish-oil.png",
  },
]
